# SPDX-License-Identifier: GPL-2.0

spinand-objs := core.o otp.o
obj-$(CONFIG_MTD_SPI_NAND) += spinand.o

spinand-$(CONFIG_MTD_SPI_NAND_ALLIANCEMEMORY)	+= alliancememory.o
spinand-$(CONFIG_MTD_SPI_NAND_ATO)		+= ato.o
spinand-$(CONFIG_MTD_SPI_NAND_ESMT)		+= esmt.o
spinand-$(CONFIG_MTD_SPI_NAND_ETRON)		+= etron.o
spinand-$(CONFIG_MTD_SPI_NAND_FMSH)		+= fmsh.o
spinand-$(CONFIG_MTD_SPI_NAND_FORESEE)		+= foresee.o
spinand-$(CONFIG_MTD_SPI_NAND_GIGADEVICE)	+= gigadevice.o
spinand-$(CONFIG_MTD_SPI_NAND_ISSI)		+= issi.o
spinand-$(CONFIG_MTD_SPI_NAND_MACRONIX)		+= macronix.o
spinand-$(CONFIG_MTD_SPI_NAND_MICRON)		+= micron.o
spinand-$(CONFIG_MTD_SPI_NAND_PARAGON)		+= paragon.o
spinand-$(CONFIG_MTD_SPI_NAND_SKYHIGH)		+= skyhigh.o
spinand-$(CONFIG_MTD_SPI_NAND_TOSHIBA)		+= toshiba.o
spinand-$(CONFIG_MTD_SPI_NAND_WINBOND)		+= winbond.o
spinand-$(CONFIG_MTD_SPI_NAND_XTX)		+= xtx.o
