# SPDX-License-Identifier: GPL-2.0

obj-y += helpers.o upgrade.o
obj-$(CONFIG_WEBUI_FAILSAFE_ADVANCED) += sysinfo.o
obj-$(CONFIG_WEBUI_FAILSAFE_CONSOLE) += console.o
obj-$(CONFIG_WEBUI_FAILSAFE_ENV) += env.o
obj-$(CONFIG_WEBUI_FAILSAFE_UBI) += ubi.o
obj-$(CONFIG_WEBUI_FAILSAFE_FLASH) += flash.o
obj-$(CONFIG_WEBUI_FAILSAFE_NAND_RAW) += nand_raw.o
obj-$(CONFIG_WEBUI_FAILSAFE_FLASH_LAYOUT) += layout.o
obj-$(CONFIG_WEBUI_FAILSAFE_SIMG) += simg.o
obj-$(CONFIG_WEBUI_FAILSAFE_UI_BOOTSTRAP) += theme.o
