// SPDX-License-Identifier: GPL-2.0-only
/*
 * Copyright (c) 2024 AIROHA Inc
 * Author: Zhi You <yuzhii0718@outlook.com>
 *
 * U-Boot MTD glue for the parallel (raw) NAND interface of the Airoha/EcoNet
 * NFI controller.
 *
 * The controller specific parts live in spi_nfi.c, spi_ecc.c,
 * parallel_nand_flash.c and parallel_nand_flash_table.c, all ported from the
 * EcoNet vendor driver.  This file only
 *   - maps the NFI / ECC register windows and enables the flash clock,
 *   - checks that the boot strap really selected the parallel interface,
 *   - brings the ECC block up for the detected device (the "enable_dma()" and
 *     "SPI_NAND_Flash_Init()" configuration of the vendor driver),
 *   - turns the page level backend into a struct mtd_info driven through
 *     UCLASS_MTD.
 *
 * Controller ECC / OOB model
 * --------------------------
 * The interface runs "auto FDM" with the hardware ECC engine enabled.  Every
 * 512 byte sector of the spare area is split between
 *   - fdm_num user bytes (8), exchanged with the controller through the FDM
 *     registers (SPI_NFI_{Read,Write}_SPI_NAND_FDM()) and exposed to MTD as the
 *     OOB area of the device, and
 *   - ECC parity bytes generated by the hardware, which cannot be read back nor
 *     written by software.
 * mtd->oobsize therefore only covers the accessible (FDM) part of the spare
 * area, mtd->oobavail removes the first byte of every sector used as the
 * manufacturer bad block marker.
 *
 * Concurrency
 * -----------
 * U-Boot runs the shell, so the controller does not need to be protected against
 * re-entrancy. Note that the erase path calls back into the bad block check, which
 * reads a page through the very same page buffer, so a plain mutex around the MTD
 * callbacks would deadlock anyway.
 */

/*======================================================================================
 * MODULE NAME: nand
 * FILE NAME: airoha_pnand.c
 * VERSION: 1.00
 * PURPOSE: MTD glue driver for the Airoha/EcoNet parallel NAND controller.
 *======================================================================================
 */

#include <clk.h>
#include <cpu_func.h>
#include <dm.h>
#include <dm/device_compat.h>
#include <dm/pinctrl.h>
#include <dm/read.h>
#include <linux/bitops.h>
#include <linux/err.h>
#include <linux/io.h>
#include <linux/mtd/mtd.h>
#include <linux/printk.h>
#include <linux/string.h>
#include <linux/types.h>
#include <malloc.h>
#include <mapmem.h>

#include "airoha_spi_ecc.h"
#include "airoha_spi_nand_flash.h"
#include "airoha_spi_nfi.h"
#include "parallel_nand_flash.h"

/* Register bases shared with spi_nfi.c and spi_ecc.c. */
unsigned long airoha_nfi_base;
unsigned long airoha_ecc_base;

/* NFI block mode strap: bit 2 selects SPI mode, clear means parallel NAND. */
#define AIROHA_NFI_SNF_NFI_CNFG		0x055c
#define AIROHA_NFI_SNF_NFI_CNFG_SPI_MODE	BIT(2)

/* Upper bounds of the supported devices, in line with _SPI_NAND_PAGE_SIZE and
 * _SPI_NAND_OOB_SIZE of the vendor driver.
 */
#define AIROHA_PNAND_MAX_PAGESIZE	4096
#define AIROHA_PNAND_MAX_OOBSIZE	256

/* FDM bytes per sector and ECC protected FDM bytes, fixed by the vendor
 * configuration (SPI_NAND_Flash_Init()).
 */
#define AIROHA_PNAND_FDM_NUM		8
#define AIROHA_PNAND_FDM_ECC_NUM	8

/* Number of polls used while waiting for the ECC decoder to finish. */
#define AIROHA_PNAND_ECC_DONE_RETRY	1000000

#ifndef ARCH_DMA_MINALIGN
#define ARCH_DMA_MINALIGN		64
#endif

struct airoha_pnand_priv {
	struct udevice *dev;
	struct mtd_info *mtd;
	struct clk *clk;

	/* page_size data followed by priv->fdm_bytes of raw FDM bytes */
	u8 *pagebuf;
	size_t pagebuf_size;

	struct SPI_NAND_FLASH_INFO_T info;
	SPI_NFI_CONF_T nfi_conf;
	SPI_ECC_ENCODE_CONF_T enc_conf;
	SPI_ECC_DECODE_CONF_T dec_conf;

	u32 sec_num;		/* 512 byte sectors per page */
	u32 fdm_num;		/* accessible OOB bytes per sector */
	u32 fdm_bytes;		/* accessible OOB bytes per page */
	u32 spare_size;		/* spare bytes per sector, FDM + parity */
	u32 dma_size;		/* bytes the controller moves per page */
	u32 pages_per_block;
};

static inline u8 *airoha_pnand_oobbuf(struct airoha_pnand_priv *priv)
{
	return priv->pagebuf + priv->info.page_size;
}

static void airoha_pnand_dma_flush(struct airoha_pnand_priv *priv)
{
	flush_dcache_range((unsigned long)priv->pagebuf,
			   (unsigned long)priv->pagebuf + priv->pagebuf_size);
}

static void airoha_pnand_dma_invalidate(struct airoha_pnand_priv *priv)
{
	invalidate_dcache_range((unsigned long)priv->pagebuf,
				(unsigned long)priv->pagebuf + priv->pagebuf_size);
}

/*------------------------------------------------------------------------------------
 * FUNCTION: static void airoha_pnand_prepare_read( struct airoha_pnand_priv *priv )
 * PURPOSE : Re-arm the controller before a page read.
 * NOTES   : PARALLEL_NFI_RESET() clears the hardware ECC / auto FDM enables of
 *           NFI_CNFG, and the previous command (status poll or erase) may have
 *           reset them, so the cached configuration has to be pushed back.
 *           The decoder is re-armed the same way the vendor read path does.
 *------------------------------------------------------------------------------------
 */
static void airoha_pnand_prepare_read(struct airoha_pnand_priv *priv)
{
	SPI_NFI_Reset();
	SPI_NFI_Set_Configure(&priv->nfi_conf);

	if (priv->nfi_conf.hw_ecc_t != SPI_NFI_CON_HW_ECC_Enable)
		return;

	if (priv->dec_conf.decode_en != SPI_ECC_DECODE_ENABLE)
		return;

	SPI_ECC_Decode_Set_Configure(&priv->dec_conf);
	SPI_ECC_Decode_Disable();
	SPI_ECC_Encode_Disable();
	SPI_ECC_Decode_Enable();
}

/*------------------------------------------------------------------------------------
 * FUNCTION: static int airoha_pnand_read_page( struct airoha_pnand_priv *priv,
 *                                  u32 page, u8 *data, u8 *oob )
 * PURPOSE : Read one page, leave the data in priv->pagebuf and the raw FDM
 *           bytes in the oob buffer of the caller.
 * RETURNS : 0 on success, -EBADMSG when the ECC engine could not correct the
 *           page, a negative errno otherwise.
 *------------------------------------------------------------------------------------
 */
static int airoha_pnand_read_page(struct airoha_pnand_priv *priv, u32 page,
				  u8 *data, u8 *oob)
{
	SPI_ECC_DECODE_STATUS_T decode_status = SPI_ECC_DECODE_STATUS_PROCESSING;
	struct mtd_info *mtd = priv->mtd;
	int ret = 0;
	u32 loop;
	u32 corrected;

	airoha_pnand_prepare_read(priv);

	airoha_pnand_dma_flush(priv);

	if (parallel_nand_dma_read(0, page, (unsigned long *)priv->pagebuf) !=
	    SPI_NAND_FLASH_RTN_NO_ERROR) {
		pr_err("airoha_pnand: page 0x%x read failed\n", page);
		return -EIO;
	}

	airoha_pnand_dma_invalidate(priv);

	if (priv->nfi_conf.hw_ecc_t == SPI_NFI_CON_HW_ECC_Enable &&
	    priv->dec_conf.decode_en == SPI_ECC_DECODE_ENABLE) {
		for (loop = 0; loop < AIROHA_PNAND_ECC_DONE_RETRY; loop++) {
			SPI_ECC_Decode_Check_Done(&decode_status,
						  priv->nfi_conf.sec_num);
			if (decode_status == SPI_ECC_DECODE_STATUS_DONE)
				break;
		}

		if (decode_status != SPI_ECC_DECODE_STATUS_DONE) {
			pr_err("airoha_pnand: page 0x%x ECC decode timeout\n", page);
			return -EIO;
		}

		/* Feed the corrected bit count of this page into ecc_stats,
		 * then check for sectors the decoder could not repair.
		 */
		corrected = SPI_ECC_DECODE_Get_Corrected_Bits();
		if (corrected)
			mtd->ecc_stats.corrected += corrected;

		if (SPI_ECC_DECODE_Check_Correction_Status() ==
		    SPI_ECC_RTN_CORRECTION_ERROR) {
			mtd->ecc_stats.failed++;
			ret = -EBADMSG;
		}
	}

	if (data)
		memcpy(data, priv->pagebuf, priv->info.page_size);

	if (oob)
		SPI_NFI_Read_SPI_NAND_FDM(oob, priv->fdm_bytes);

	return ret;
}

/*------------------------------------------------------------------------------------
 * FUNCTION: static int airoha_pnand_write_page( struct airoha_pnand_priv *priv,
 *                                  u32 page, const u8 *data, u8 *oob )
 * PURPOSE : Program one page from priv->pagebuf and the given raw FDM bytes.
 *------------------------------------------------------------------------------------
 */
static int airoha_pnand_write_page(struct airoha_pnand_priv *priv, u32 page,
				   const u8 *data, u8 *oob)
{
	if (parallel_nand_dma_write(0, page, (unsigned long *)priv->pagebuf,
				    priv->fdm_bytes, oob) !=
	    SPI_NAND_FLASH_RTN_NO_ERROR) {
		pr_err("airoha_pnand: page 0x%x program failed\n", page);
		return -EIO;
	}

	return 0;
}

/*------------------------------------------------------------------------------------
 * FUNCTION: static int airoha_pnand_erase_block( struct airoha_pnand_priv *priv,
 *                                  loff_t block )
 * PURPOSE : Erase the block starting at the given byte offset.
 *------------------------------------------------------------------------------------
 */
static int airoha_pnand_erase_block(struct airoha_pnand_priv *priv, loff_t block)
{
	if (parallel_nand_erase(block / priv->info.page_size) !=
	    SPI_NAND_FLASH_RTN_NO_ERROR) {
		pr_err("airoha_pnand: block 0x%llx erase failed\n", block);
		return -EIO;
	}

	return 0;
}

/*------------------------------------------------------------------------------------
 * MTD operations
 *------------------------------------------------------------------------------------
 */

static int airoha_pnand_mtd_erase(struct mtd_info *mtd, struct erase_info *instr)
{
	struct airoha_pnand_priv *priv = mtd->priv;
	loff_t start, end;
	int ret = 0;

	if ((instr->addr + instr->len) > mtd->size) {
		pr_debug("airoha_pnand: attempt to erase beyond end of device\n");
		return -EINVAL;
	}

	start = instr->addr & ~((loff_t)mtd->erasesize - 1);
	end = instr->addr + instr->len;
	if (end & (mtd->erasesize - 1))
		end = (end + mtd->erasesize - 1) & ~((loff_t)mtd->erasesize - 1);

	instr->state = MTD_ERASING;

	while (start < end) {
		if (!instr->scrub && mtd_block_isbad(mtd, start)) {
			instr->fail_addr = start;
			ret = -EIO;
			break;
		}

		ret = airoha_pnand_erase_block(priv, start);
		if (ret) {
			instr->fail_addr = start;
			break;
		}

		start += mtd->erasesize;
	}

	instr->state = ret ? MTD_ERASE_FAILED : MTD_ERASE_DONE;

	return ret;
}

static int airoha_pnand_mtd_read_oob(struct mtd_info *mtd, loff_t from,
				     struct mtd_oob_ops *ops)
{
	struct airoha_pnand_priv *priv = mtd->priv;
	size_t len, ooblen;
	u32 maxooblen, ooboffs;
	u32 col;
	loff_t addr;
	bool ecc_failed = false;
	int ret;

	if (!ops->oobbuf && !ops->datbuf) {
		if (ops->ooblen || ops->len)
			return -EINVAL;

		return 0;
	}

	switch (ops->mode) {
	case MTD_OPS_PLACE_OOB:
	case MTD_OPS_AUTO_OOB:
	case MTD_OPS_RAW:
		break;
	default:
		pr_debug("airoha_pnand: unsupported oob mode %u\n", ops->mode);
		return -EINVAL;
	}

	maxooblen = mtd_oobavail(mtd, ops);

	if (ops->datbuf && (from + ops->len) > mtd->size) {
		pr_debug("airoha_pnand: attempt to read beyond end of device\n");
		return -EINVAL;
	}

	if (unlikely(ops->ooboffs >= maxooblen)) {
		pr_debug("airoha_pnand: attempt to start read outside oob\n");
		return -EINVAL;
	}

	col = mtd_mod_by_ws((u64)from, mtd);
	addr = from - col;
	len = ops->len;
	ooblen = ops->ooblen;
	ooboffs = ops->ooboffs;

	ops->retlen = 0;
	ops->oobretlen = 0;

	if (len && !ops->datbuf)
		return -EINVAL;
	if (ooblen && !ops->oobbuf)
		return -EINVAL;

	while (len || ooblen) {
		size_t chklen;

		ret = airoha_pnand_read_page(priv, (u32)(addr / mtd->writesize),
					     len ? priv->pagebuf : NULL,
					     airoha_pnand_oobbuf(priv));
		if (ret == -EBADMSG)
			ecc_failed = true;
		else if (ret)
			return ret;

		if (len) {
			chklen = mtd->writesize - col;
			if (chklen > len)
				chklen = len;

			memcpy(ops->datbuf + ops->retlen, priv->pagebuf + col,
			       chklen);
			ops->retlen += chklen;
			len -= chklen;
			col = 0;
		}

		if (ooblen) {
			u8 *dst = ops->oobbuf + ops->oobretlen;
			u8 *raw = airoha_pnand_oobbuf(priv);

			chklen = maxooblen - ooboffs;
			if (chklen > ooblen)
				chklen = ooblen;

			if (ops->mode == MTD_OPS_AUTO_OOB)
				mtd_ooblayout_get_databytes(mtd, dst, raw,
							    ooboffs, chklen);
			else
				memcpy(dst, raw + ooboffs, chklen);

			ops->oobretlen += chklen;
			ooblen -= chklen;
			ooboffs = 0;
		}

		addr += mtd->writesize;
	}

	return ecc_failed ? -EBADMSG : 0;
}

static int airoha_pnand_mtd_write_oob(struct mtd_info *mtd, loff_t to,
				      struct mtd_oob_ops *ops)
{
	struct airoha_pnand_priv *priv = mtd->priv;
	size_t len, ooblen;
	u32 maxooblen, ooboffs;
	u32 col;
	loff_t addr;
	int ret = 0;

	if (!ops->oobbuf && !ops->datbuf) {
		if (ops->ooblen || ops->len)
			return -EINVAL;

		return 0;
	}

	switch (ops->mode) {
	case MTD_OPS_PLACE_OOB:
	case MTD_OPS_AUTO_OOB:
	case MTD_OPS_RAW:
		break;
	default:
		pr_debug("airoha_pnand: unsupported oob mode %u\n", ops->mode);
		return -EINVAL;
	}

	maxooblen = mtd_oobavail(mtd, ops);

	if (ops->datbuf && (to + ops->len) > mtd->size) {
		pr_debug("airoha_pnand: attempt to write beyond end of device\n");
		return -EINVAL;
	}

	if (unlikely(ops->ooboffs >= maxooblen)) {
		pr_debug("airoha_pnand: attempt to start write outside oob\n");
		return -EINVAL;
	}

	col = mtd_mod_by_ws((u64)to, mtd);
	addr = to - col;
	len = ops->len;
	ooblen = ops->ooblen;
	ooboffs = ops->ooboffs;

	ops->retlen = 0;
	ops->oobretlen = 0;

	if (len && !ops->datbuf)
		return -EINVAL;
	if (ooblen && !ops->oobbuf)
		return -EINVAL;

	while (len || ooblen) {
		size_t chklen;

		/* The controller can only program a full page: pad the
		 * untouched parts with 0xff, which is what an erased cell
		 * holds anyway.
		 */
		memset(priv->pagebuf, 0xff, mtd->writesize);
		memset(airoha_pnand_oobbuf(priv), 0xff, priv->fdm_bytes);

		if (len) {
			chklen = mtd->writesize - col;
			if (chklen > len)
				chklen = len;

			memcpy(priv->pagebuf + col, ops->datbuf + ops->retlen,
			       chklen);
			ops->retlen += chklen;
			len -= chklen;
			col = 0;
		}

		if (ooblen) {
			u8 *src = ops->oobbuf + ops->oobretlen;
			u8 *raw = airoha_pnand_oobbuf(priv);

			chklen = maxooblen - ooboffs;
			if (chklen > ooblen)
				chklen = ooblen;

			if (ops->mode == MTD_OPS_AUTO_OOB)
				mtd_ooblayout_set_databytes(mtd, src, raw,
							    ooboffs, chklen);
			else
				memcpy(raw + ooboffs, src, chklen);

			ops->oobretlen += chklen;
			ooblen -= chklen;
			ooboffs = 0;
		}

		airoha_pnand_dma_flush(priv);

		ret = airoha_pnand_write_page(priv, (u32)(addr / mtd->writesize),
					      priv->pagebuf,
					      airoha_pnand_oobbuf(priv));
		if (ret)
			return ret;

		airoha_pnand_dma_invalidate(priv);

		addr += mtd->writesize;
	}

	return 0;
}

static int airoha_pnand_mtd_read(struct mtd_info *mtd, loff_t from, size_t len,
				 size_t *retlen, u_char *buf)
{
	struct mtd_oob_ops ops = {
		.mode = MTD_OPS_PLACE_OOB,
		.datbuf = buf,
		.len = len,
	};
	int ret;

	ret = airoha_pnand_mtd_read_oob(mtd, from, &ops);

	if (retlen)
		*retlen = ops.retlen;

	return ret;
}

static int airoha_pnand_mtd_write(struct mtd_info *mtd, loff_t to, size_t len,
				  size_t *retlen, const u_char *buf)
{
	struct mtd_oob_ops ops = {
		.mode = MTD_OPS_PLACE_OOB,
		.datbuf = (u8 *)buf,
		.len = len,
	};
	int ret;

	ret = airoha_pnand_mtd_write_oob(mtd, to, &ops);

	if (retlen)
		*retlen = ops.retlen;

	return ret;
}

static int airoha_pnand_mtd_block_isbad(struct mtd_info *mtd, loff_t ofs)
{
	struct airoha_pnand_priv *priv = mtd->priv;
	u8 *oob = airoha_pnand_oobbuf(priv);
	loff_t block = ofs & ~((loff_t)mtd->erasesize - 1);
	int ret;

	/* The manufacturer bad block marker is the first spare byte of the
	 * first page of the block, which the controller exposes as FDM byte 0
	 * of sector 0.
	 *
	 * An uncorrectable ECC error (-EBADMSG) does not prevent the verdict:
	 * the FDM bytes are read back from the controller after the decoder has
	 * been checked, so they are valid even then, and this is exactly the
	 * case where a bad block has to be reported.  Only a hard controller
	 * failure leaves the buffer undefined.
	 */
	ret = airoha_pnand_read_page(priv, (u32)(block / mtd->writesize), NULL, oob);
	if (ret < 0 && ret != -EBADMSG)
		return ret;

	return oob[0] != 0xff;
}

static int airoha_pnand_mtd_block_markbad(struct mtd_info *mtd, loff_t ofs)
{
	struct airoha_pnand_priv *priv = mtd->priv;
	loff_t block = ofs & ~((loff_t)mtd->erasesize - 1);
	int ret;

	/* The marker can only clear bits, so the block has to be erased first.
	 * airoha_pnand_erase_block() is used instead of mtd_erase() to avoid
	 * the bad block check of the generic erase path.
	 */
	ret = airoha_pnand_erase_block(priv, block);
	if (ret)
		return ret;

	memset(priv->pagebuf, 0xff, priv->info.page_size);
	memset(airoha_pnand_oobbuf(priv), 0xff, priv->fdm_bytes);
	airoha_pnand_oobbuf(priv)[0] = 0x00;

	airoha_pnand_dma_flush(priv);

	ret = airoha_pnand_write_page(priv, (u32)(block / mtd->writesize),
				      priv->pagebuf, airoha_pnand_oobbuf(priv));

	airoha_pnand_dma_invalidate(priv);

	return ret;
}

/* The OOB area exposed to MTD is the FDM part of the spare area, fdm_num bytes
 * per sector, laid out sector by sector.  Byte 0 of every sector is kept out of
 * the free area: it carries the manufacturer bad block marker.
 */
static int airoha_pnand_ooblayout_free(struct mtd_info *mtd, int section,
				       struct mtd_oob_region *oobfree)
{
	struct airoha_pnand_priv *priv = mtd->priv;

	if (section >= priv->sec_num)
		return -ERANGE;

	oobfree->offset = section * priv->fdm_num + 1;
	oobfree->length = priv->fdm_num - 1;

	return 0;
}

static int airoha_pnand_ooblayout_ecc(struct mtd_info *mtd, int section,
				      struct mtd_oob_region *oobecc)
{
	/* The ECC parity bytes belong to the hardware and are not reachable
	 * through the FDM registers, there is no ECC region to describe.
	 */
	return -ERANGE;
}

static const struct mtd_ooblayout_ops airoha_pnand_ooblayout = {
	.rfree = airoha_pnand_ooblayout_free,
	.ecc = airoha_pnand_ooblayout_ecc,
};

/*------------------------------------------------------------------------------------
 * FUNCTION: static int airoha_pnand_setup_ecc( struct airoha_pnand_priv *priv )
 * PURPOSE : Translate the detected device into the controller ECC / FDM
 *           configuration and program it.
 * NOTES   : Mirrors the "Using SoC ECC" branch of the vendor
 *           SPI_NAND_Flash_Init() plus enable_dma().
 *------------------------------------------------------------------------------------
 */
static int airoha_pnand_setup_ecc(struct airoha_pnand_priv *priv)
{
	u32 sec_num, spare_size, enc_ab, dec_ab;

	sec_num = priv->info.page_size / 512;
	if (sec_num != 4 && sec_num != 8) {
		dev_err(priv->dev, "unsupported page size 0x%x\n",
			priv->info.page_size);
		return -ENOTSUPP;
	}

	switch (priv->info.soc_ecc_ability) {
	case 4:
		spare_size = SPI_NFI_CONF_SPARE_SIZE_16BYTE;
		enc_ab = SPI_ECC_ENCODE_ABILITY_4BITS;
		dec_ab = SPI_ECC_DECODE_ABILITY_4BITS;
		break;
	case 8:
		spare_size = SPI_NFI_CONF_SPARE_SIZE_28BYTE;
		enc_ab = SPI_ECC_ENCODE_ABILITY_8BITS;
		dec_ab = SPI_ECC_DECODE_ABILITY_8BITS;
		break;
	case 12:
		spare_size = SPI_NFI_CONF_SPARE_SIZE_28BYTE;
		enc_ab = SPI_ECC_ENCODE_ABILITY_12BITS;
		dec_ab = SPI_ECC_DECODE_ABILITY_12BITS;
		break;
	default:
		dev_err(priv->dev, "unsupported ECC ability %u\n",
			priv->info.soc_ecc_ability);
		return -ENOTSUPP;
	}

	/* The parity has to fit into the spare area next to the FDM bytes,
	 * same check as the vendor auto sizing code.
	 */
	if ((spare_size - AIROHA_PNAND_FDM_NUM) * 8 < (13 * dec_ab)) {
		dev_err(priv->dev,
			"spare size %u does not fit ECC ability %u\n",
			spare_size, dec_ab);
		return -ENOTSUPP;
	}

	if (spare_size > (u32)(priv->info.oob_size / sec_num)) {
		dev_err(priv->dev, "spare size %u exceeds the device spare area\n",
			spare_size);
		return -ENOTSUPP;
	}

	priv->sec_num = sec_num;
	priv->fdm_num = AIROHA_PNAND_FDM_NUM;
	priv->fdm_bytes = sec_num * AIROHA_PNAND_FDM_NUM;
	priv->spare_size = spare_size;
	/* The controller moves one whole sector (512 data + spare) at a time. */
	priv->dma_size = priv->info.page_size + sec_num * spare_size;

	priv->nfi_conf.auto_fdm_t = SPI_NFI_CON_AUTO_FDM_Enable;
	priv->nfi_conf.hw_ecc_t = SPI_NFI_CON_HW_ECC_Enable;
	priv->nfi_conf.dma_burst_t = SPI_NFI_CON_DMA_BURST_Enable;
	priv->nfi_conf.fdm_num = AIROHA_PNAND_FDM_NUM;
	priv->nfi_conf.fdm_ecc_num = AIROHA_PNAND_FDM_ECC_NUM;
	priv->nfi_conf.spare_size_t = spare_size;
	priv->nfi_conf.page_size_t = priv->info.page_size;
	priv->nfi_conf.sec_num = sec_num;
	priv->nfi_conf.cus_sec_size_en_t = SPI_NFI_CONF_CUS_SEC_SIZE_Disable;
	priv->nfi_conf.sec_size = 0;

	priv->enc_conf.encode_en = SPI_ECC_ENCODE_ENABLE;
	priv->enc_conf.encode_ecc_abiliry = enc_ab;
	priv->enc_conf.encode_block_size = 512 + AIROHA_PNAND_FDM_ECC_NUM;

	priv->dec_conf.decode_en = SPI_ECC_DECODE_ENABLE;
	priv->dec_conf.decode_ecc_abiliry = dec_ab;
	priv->dec_conf.decode_block_size =
		((AIROHA_PNAND_FDM_ECC_NUM + 512) * 8) + (dec_ab * 13);

	SPI_NFI_Init();
	SPI_NFI_Set_Configure(&priv->nfi_conf);

	/* EN7581 (HIR 0xE) is newer than EN751627 (HIR 0x9), which is the
	 * condition the vendor enable_dma() uses to invert the ECC data source.
	 */
	SPI_NFI_ECC_DATA_SOURCE_INV(SPI_NFI_CONF_ECC_DATA_SOURCE_INV_ENABLE);

	SPI_ECC_Encode_Init();
	SPI_ECC_Decode_Init();
	SPI_ECC_Encode_Set_Configure(&priv->enc_conf);
	SPI_ECC_Decode_Set_Configure(&priv->dec_conf);

	return 0;
}

/*------------------------------------------------------------------------------------
 * NFI AC timing (NFI_ACCCON)
 *
 * NFI_ACCCON holds seven cycle counts of the NFI's APB clock (150 MHz on the
 * AN7581/AN7583):
 *
 *   31:28 poecs   27:22 precs   21:16 c2r   15:12 w2r
 *   11:8  wh       7:4   wst      3:0   rlt
 *
 * The device table carries a calibrated whole value for the detected device.
 * A board may instead state the raw register value, ask for an ONFI async SDR
 * timing mode (the field formulas below are the ones mtk_nand.c uses for the
 * same register), or override single fields on top of the device table value.
 *
 * Measured byte time on an AN7581 EVB is (rlt + wh + 2) * 6.67ns + 20ns, so the
 * modes with a short RE# low time also need the data sampling strobe of
 * NFI_DEBUG_CON1: with rlt=1, wh=1 and strobe=1 the same board reads at
 * 20.5 MiB/s against 10.1 MiB/s for the device table value.
 *------------------------------------------------------------------------------------
 */
#define AIROHA_NFI_ACCCON		0x00c
#define AIROHA_NFI_DEBUG_CON1		0x220
#define AIROHA_NFI_STROBE_SHIFT		3
#define AIROHA_NFI_STROBE_MAX		3

/* APB clock the AC timing fields count cycles of. */
#define AIROHA_PNAND_APB_HZ		150000000

/* ONFI async SDR timings in ps, the values of nand_timings.c. */
struct airoha_pnand_sdr_timing {
	u32 tALH, tALS, tCLH, tCLS, tRC, tREA, tREH, tRP, tWC, tWH, tWHR, tWP;
};

static const struct airoha_pnand_sdr_timing airoha_pnand_sdr[6] = {
	{ 20000, 50000, 20000, 50000, 100000, 40000, 30000, 50000, 100000, 30000, 120000, 50000 },
	{ 10000, 25000, 10000, 25000,  50000, 30000, 15000, 25000,  45000, 15000,  80000, 25000 },
	{ 10000, 15000, 10000, 15000,  35000, 25000, 15000, 17000,  35000, 15000,  80000, 17000 },
	{  5000, 10000,  5000, 10000,  30000, 20000, 10000, 15000,  30000, 10000,  80000, 15000 },
	{  5000, 10000,  5000, 10000,  25000, 20000, 10000, 12000,  25000, 10000,  80000, 12000 },
	{  5000, 10000,  5000, 10000,  20000, 16000,  7000, 10000,  20000,  7000,  80000, 10000 },
};

static u32 airoha_pnand_ac_cycles(u32 ps)
{
	u32 rate_khz = AIROHA_PNAND_APB_HZ / 1000;
	u32 ns = DIV_ROUND_UP(ps, 1000);

	return DIV_ROUND_UP(ns * rate_khz, 1000000);
}

/*------------------------------------------------------------------------------------
 * FUNCTION: static u32 airoha_pnand_accon_from_mode( u8 mode, u32 *strobe )
 * PURPOSE : Compose NFI_ACCCON, and the sampling strobe it needs, for one ONFI
 *           async SDR timing mode.
 *------------------------------------------------------------------------------------
 */
static u32 airoha_pnand_accon_from_mode(u8 mode, u32 *strobe)
{
	const struct airoha_pnand_sdr_timing *t = &airoha_pnand_sdr[mode];
	u32 rate_khz = AIROHA_PNAND_APB_HZ / 1000;
	u32 poecs, precs, w2r, wh, wst, rlt, high_ps, twst_ps, trlt_ps;
	u32 tsel = 0;

	poecs = airoha_pnand_ac_cycles(max(t->tALH, t->tCLH)) & 0xf;
	precs = airoha_pnand_ac_cycles(max(t->tALS, t->tCLS)) & 0x3f;
	w2r = DIV_ROUND_UP(airoha_pnand_ac_cycles(t->tWHR) - 1, 2) & 0xf;
	wh = (airoha_pnand_ac_cycles(max(t->tREH, t->tWH)) - 1) & 0xf;

	/* RE#/WE# high time the wh field above programs, in ps. */
	high_ps = (wh + 1) * 1000000 / rate_khz * 1000;

	twst_ps = t->tWC > high_ps ? t->tWC - high_ps : 0;
	wst = (airoha_pnand_ac_cycles(max(t->tWP, twst_ps)) - 1) & 0xf;

	trlt_ps = t->tRC > high_ps ? t->tRC - high_ps : 0;
	rlt = (airoha_pnand_ac_cycles(max(trlt_ps, t->tRP)) - 1) & 0xf;

	/* The device drives valid data tREA after RE# falls.  If the RE# low
	 * time is shorter than that, the sample point has to move into the high
	 * phase; when even the strobe range is not enough, RE# has to stay low
	 * for longer.
	 */
	if ((rlt + 1) * 1000000 / rate_khz * 1000 < t->tREA) {
		tsel = airoha_pnand_ac_cycles(t->tREA) - (rlt + 1);
		if (tsel > AIROHA_NFI_STROBE_MAX) {
			rlt += tsel - AIROHA_NFI_STROBE_MAX;
			tsel = AIROHA_NFI_STROBE_MAX;
		}
	}

	*strobe = tsel;

	return poecs << 28 | precs << 22 | w2r << 12 | wh << 8 | wst << 4 | rlt;
}

static void airoha_pnand_accon_set_field(struct udevice *dev, const char *name,
					 u32 shift, u32 mask, u32 val,
					 u32 *timing)
{
	if (val > mask) {
		dev_warn(dev, "%s = %u is out of range, clamped to %u\n",
			 name, val, mask);
		val = mask;
	}

	*timing = (*timing & ~(mask << shift)) | ((val & mask) << shift);
}

static void airoha_pnand_set_strobe(u32 strobe)
{
	u32 reg = readl(airoha_nfi_base + AIROHA_NFI_DEBUG_CON1);

	reg &= ~(AIROHA_NFI_STROBE_MAX << AIROHA_NFI_STROBE_SHIFT);
	reg |= (strobe & AIROHA_NFI_STROBE_MAX) << AIROHA_NFI_STROBE_SHIFT;

	writel(reg, airoha_nfi_base + AIROHA_NFI_DEBUG_CON1);
}

/*------------------------------------------------------------------------------------
 * FUNCTION: static void airoha_pnand_apply_ac_timing( struct udevice *dev )
 * PURPOSE : Apply the AC timing configuration of the device tree, if any.
 * NOTES   : Runs after the backend probe, so it takes precedence over the value
 *           the device table programmed.  Properties, in decreasing priority:
 *
 *           1) airoha,ac-timing         raw NFI_ACCCON value
 *           2) airoha,nand-timing-mode  ONFI async SDR timing mode 0..5
 *           3) airoha,ac-timing-<field> single fields on top of 1) or 2) or,
 *                                       when neither is given, of the value of
 *                                       the device table
 *              airoha,ac-timing-strobe  data sampling delay in cycles (0..3)
 *
 *           Without any of them nothing is written and the device table default
 *           stays in place (see CONFIG_AIROHA_PARALLEL_NAND_TIMING).
 *------------------------------------------------------------------------------------
 */
static void airoha_pnand_apply_ac_timing(struct udevice *dev)
{
	static const struct {
		const char *name;
		u32 shift, mask;
	} fields[] = {
		{ "airoha,ac-timing-poecs", 28, 0x0f },
		{ "airoha,ac-timing-precs", 22, 0x3f },
		{ "airoha,ac-timing-c2r",   16, 0x3f },
		{ "airoha,ac-timing-w2r",   12, 0x0f },
		{ "airoha,ac-timing-wh",     8, 0x0f },
		{ "airoha,ac-timing-wst",    4, 0x0f },
		{ "airoha,ac-timing-rlt",    0, 0x0f },
	};
	u32 timing = 0, strobe = 0, val, mode = 0;
	bool have_timing = false, have_strobe = false;
	bool from_mode = false, from_field = false;
	char src[64];
	int len;
	unsigned int i;

	if (!dev_read_u32(dev, "airoha,ac-timing", &timing)) {
		/* All fields at zero leaves no setup/hold margin at all and
		 * 0xffffffff is the hardware reset default, neither is usable.
		 */
		if (!timing || timing == 0xffffffff) {
			dev_warn(dev, "invalid airoha,ac-timing 0x%08x, ignored\n",
				 timing);
		} else {
			have_timing = true;
		}
	}

	if (!have_timing &&
	    !dev_read_u32(dev, "airoha,nand-timing-mode", &val)) {
		if (val > ARRAY_SIZE(airoha_pnand_sdr) - 1) {
			dev_warn(dev, "airoha,nand-timing-mode %u is out of range, ignored\n",
				 val);
		} else {
			timing = airoha_pnand_accon_from_mode(val, &strobe);
			mode = val;
			from_mode = true;
			have_timing = true;
			have_strobe = true;
		}
	}

	for (i = 0; i < ARRAY_SIZE(fields); i++) {
		if (dev_read_u32(dev, fields[i].name, &val))
			continue;

		if (!have_timing) {
			timing = parallel_nand_get_timing();
			have_timing = true;
		}

		airoha_pnand_accon_set_field(dev, fields[i].name, fields[i].shift,
					     fields[i].mask, val, &timing);
		from_field = true;
	}

	if (!dev_read_u32(dev, "airoha,ac-timing-strobe", &val)) {
		if (val > AIROHA_NFI_STROBE_MAX) {
			dev_warn(dev, "airoha,ac-timing-strobe %u is out of range, ignored\n",
				 val);
		} else {
			strobe = val;
			have_strobe = true;
		}
	}

	if (!have_timing && !have_strobe)
		return;

	if (have_timing) {
		PARALLEL_NFI_SET_TIMING(timing);

		if (from_mode)
			len = snprintf(src, sizeof(src),
				       "airoha,nand-timing-mode = %u", mode);
		else if (from_field)
			len = snprintf(src, sizeof(src), "device table value");
		else
			len = snprintf(src, sizeof(src), "airoha,ac-timing");

		if (from_field && len > 0 && len < sizeof(src))
			snprintf(src + len, sizeof(src) - len,
				 " + airoha,ac-timing-*");

		dev_info(dev, "AC timing 0x%08x rlt=%u wst=%u wh=%u w2r=%u c2r=%u precs=%u poecs=%u (device tree: %s)\n",
			 timing, timing & 0xf, (timing >> 4) & 0xf,
			 (timing >> 8) & 0xf, (timing >> 12) & 0xf,
			 (timing >> 16) & 0x3f, (timing >> 22) & 0x3f,
			 (timing >> 28) & 0xf, src);
	}

	if (have_strobe) {
		airoha_pnand_set_strobe(strobe);

		dev_info(dev, "AC timing strobe %u (device tree: %s)\n", strobe,
			 from_mode ? "airoha,nand-timing-mode"
				   : "airoha,ac-timing-strobe");
	}
}

/*------------------------------------------------------------------------------------
 * FUNCTION: static int airoha_pnand_probe( struct udevice *dev )
 * PURPOSE : Bind the parallel NAND interface and register it as an MTD device.
 *------------------------------------------------------------------------------------
 */
static int airoha_pnand_probe(struct udevice *dev)
{
	struct airoha_pnand_priv *priv = dev_get_priv(dev);
	struct mtd_info *mtd = dev_get_uclass_priv(dev);
	fdt_addr_t base;
	u32 snf_nfi_cnfg;
	int ret;

	base = dev_read_addr_name(dev, "nfi");
	if (base == FDT_ADDR_T_NONE) {
		dev_err(dev, "missing 'nfi' register range\n");
		return -EINVAL;
	}
	airoha_nfi_base = (unsigned long)map_sysmem(base, 0);

	base = dev_read_addr_name(dev, "ecc");
	if (base == FDT_ADDR_T_NONE) {
		dev_err(dev, "missing 'ecc' register range\n");
		return -EINVAL;
	}
	airoha_ecc_base = (unsigned long)map_sysmem(base, 0);

	priv->dev = dev;
	priv->mtd = mtd;

	priv->clk = devm_clk_get(dev, "spi");
	if (IS_ERR(priv->clk)) {
		dev_err(dev, "unable to get the spi clock\n");
		return PTR_ERR(priv->clk);
	}
	clk_enable(priv->clk);

	ret = pinctrl_select_state(dev, "default");
	if (ret)
		dev_warn(dev, "failed to select the default pinctrl state: %d\n",
			 ret);

	/* The NFI block drives either SPI-NAND or a parallel NAND bus, the mode
	 * comes from the boot strap and is reported by SNF_NFI_CNFG bit 2.  Only
	 * claim the block when the hardware really is in parallel mode,
	 * otherwise the &snfi and the &nand nodes would fight over it.
	 */
	snf_nfi_cnfg = readl((void __iomem *)(airoha_nfi_base +
					      AIROHA_NFI_SNF_NFI_CNFG));
	dev_dbg(dev, "SNF_NFI_CNFG=0x%08x\n", snf_nfi_cnfg);
	if (snf_nfi_cnfg & AIROHA_NFI_SNF_NFI_CNFG_SPI_MODE) {
		dev_err(dev, "NFI is in SPI-NAND mode, not probing parallel NAND\n");
		return -ENODEV;
	}

	/* The backend keeps the probed geometry in parallel_nand_info and uses
	 * it for every access helper, so it must be the structure handed to
	 * parallel_nand_probe().  A local copy is kept for readability, both
	 * are identical and never change after the probe.
	 */
	if (parallel_nand_probe(&parallel_nand_info) !=
	    SPI_NAND_FLASH_RTN_NO_ERROR)
		return -ENODEV;

	priv->info = parallel_nand_info;

	/* A board can override the AC timing the backend just programmed from
	 * the device table, see "airoha,ac-timing".
	 */
	airoha_pnand_apply_ac_timing(dev);

	if (priv->info.page_size > AIROHA_PNAND_MAX_PAGESIZE ||
	    priv->info.oob_size > AIROHA_PNAND_MAX_OOBSIZE ||
	    !priv->info.page_size || !priv->info.erase_size) {
		dev_err(dev, "unsupported geometry, page=0x%x oob=0x%x\n",
			priv->info.page_size, priv->info.oob_size);
		return -ENOTSUPP;
	}

	ret = airoha_pnand_setup_ecc(priv);
	if (ret)
		return ret;

	priv->pages_per_block = priv->info.erase_size / priv->info.page_size;

	/* The DMA region has to cover what the controller moves, the raw FDM
	 * bytes live right behind the page data.
	 */
	priv->pagebuf_size = ALIGN(priv->dma_size, ARCH_DMA_MINALIGN);
	priv->pagebuf = memalign(ARCH_DMA_MINALIGN, priv->pagebuf_size);
	if (!priv->pagebuf) {
		dev_err(dev, "failed to allocate the page buffer\n");
		return -ENOMEM;
	}

	/* struct mtd_info::name is a plain char * in U-Boot, the name comes from
	 * the const device table (same assignment as nand_base.c does).
	 */
	mtd->name = (char *)priv->info.ptr_name;
	mtd->dev = dev;
	mtd->priv = priv;
	mtd->type = MTD_NANDFLASH;
	mtd->flags = MTD_CAP_NANDFLASH;

	mtd->size = priv->info.device_size;
	mtd->erasesize = priv->info.erase_size;
	mtd->writesize = priv->info.page_size;
	mtd->writebufsize = priv->info.page_size;

	/* Only the FDM part of the spare area is accessible, see the file
	 * header.  Byte 0 of every sector holds the bad block marker and is
	 * therefore not part of the free area.
	 */
	mtd->oobsize = priv->fdm_bytes;
	mtd->oobavail = priv->sec_num * (priv->fdm_num - 1);

	mtd->ecc_step_size = 512;
	mtd->ecc_strength = priv->info.soc_ecc_ability;

	mtd_set_ooblayout(mtd, &airoha_pnand_ooblayout);

	mtd->_read = airoha_pnand_mtd_read;
	mtd->_write = airoha_pnand_mtd_write;
	mtd->_erase = airoha_pnand_mtd_erase;
	mtd->_read_oob = airoha_pnand_mtd_read_oob;
	mtd->_write_oob = airoha_pnand_mtd_write_oob;
	mtd->_block_isbad = airoha_pnand_mtd_block_isbad;
	mtd->_block_markbad = airoha_pnand_mtd_block_markbad;

	ret = add_mtd_device(mtd);
	if (ret) {
		dev_err(dev, "failed to add the MTD device\n");
		free(priv->pagebuf);
		priv->pagebuf = NULL;
		return ret;
	}

	dev_info(dev, "parallel NAND %s: %llu MiB, page 0x%x, block 0x%x, oob %u/%u\n",
		 priv->info.ptr_name, (u64)priv->info.device_size >> 20,
		 priv->info.page_size, priv->info.erase_size,
		 mtd->oobavail, mtd->oobsize);

	return 0;
}

static const struct udevice_id airoha_pnand_ids[] = {
	{ .compatible = "airoha,en7581-nand" },
	{ }
};

U_BOOT_DRIVER(airoha_pnand) = {
	.name = "airoha-pnand",
	.id = UCLASS_MTD,
	.of_match = airoha_pnand_ids,
	.priv_auto = sizeof(struct airoha_pnand_priv),
	.probe = airoha_pnand_probe,
};
