# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_AIROHA_PARALLEL_NAND) += airoha_pnand.o
obj-$(CONFIG_AIROHA_PARALLEL_NAND) += parallel_nand_flash.o
obj-$(CONFIG_AIROHA_PARALLEL_NAND) += parallel_nand_flash_table.o
obj-$(CONFIG_AIROHA_PARALLEL_NAND) += spi_ecc.o
obj-$(CONFIG_AIROHA_PARALLEL_NAND) += spi_nfi.o
