# SPDX-License-Identifier: GPL-2.0+

obj-y += cpu.o
obj-$(CONFIG_TARGET_EN751221) += en751221/
obj-$(CONFIG_TARGET_EN7528)   += en7528/
obj-$(CONFIG_TARGET_EN751627) += en7528/
obj-$(CONFIG_TARGET_EN7580)   += en7580/
